config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'facilities#index'
  resources :facilities, only: [:index]
  resources :users, only: [:show, :edit]
  resources :messages

  get '/recipients/search' => 'users#search'
  put '/profiles'          => 'users#update'
  get '/facilities/search' => 'facilities#search'
  get '/facilities/zip_search' => 'facilities#zip_search'
end

app/models/address.rb
class Address < ActiveRecord::Base
  # Bi Bi viet code nhu Venus
  belongs_to :owner, polymorphic: true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  has_many :addresses, as: :owner
  belongs_to :user # facility administrator

  def administrator_name
    "#{self.user.first_name} #{self.user.last_name}" if self.user
  end

  def administrator=(admin)
    self.user = admin
  end

  def licensed_date_string
    license_first_date&.strftime('%b-%d-%Y')
  end

  def closed_date_string
    closed_date&.strftime('%b-%d-%Y')
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'

  has_many :messages_users, dependent: :destroy
  has_many :recipients, through: :messages_users

  def recipients_array
    recipients.map { |x| "#{x.name} (#{x.email})" }
  end

  def sent_date
    created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%b-%d-%Y %I:%M:%S %p %z')
  end
end

app/models/messages_user.rb
class MessagesUser < ActiveRecord::Base
  belongs_to :received_message, class_name: 'Message', foreign_key: 'message_id'
  belongs_to :recipient, class_name: 'User', foreign_key: 'user_id'
end

app/models/role.rb
class Role < ActiveRecord::Base
  ROLES = {
    parent:         :PARENT,
    child:          :CHILD,
    case_worker:    :CASE_WORKER,
    facility_admin: :FACILITY_ADMIN,
    system_admin:   :SYSTEM_ADMIN
  }

  has_many :roles_users
  has_many :users, through: :roles_users
end

app/models/roles_user.rb
class RolesUser < ActiveRecord::Base
  # Bi Bi viet code nhu Venus
  belongs_to :user
  belongs_to :role
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses, as: :owner

  has_many :roles_users
  has_many :roles, through: :roles_users

  belongs_to :facility # only for facility_admin, case_worker and children

  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'

  has_many :messages_users
  has_many :received_messages, through: :messages_users

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    user_path(:no_id)
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :zip_search, :search]

  def index
    @facilities = Facility.includes(:addresses).all
  end

  def zip_search
    search_param = params[:q]
    zips = Address.where("zip like '#{search_param.downcase}%'").map(&:zip).to_a.uniq.sort

    results = zips.map { |x| {text: x, id: x } }
    render json: { items: results}
  end

  def search
    zipcodes = params[:zipcodes]
    if (!zipcodes)
      @facilities = Facility.includes(:addresses).where(facility_status: 'LICENSED')
    else
      facilities = Address.includes( owner: :addresses ).where("zip in (?) AND owner_type = 'Facility'", zipcodes).to_a.group_by(&:owner).keys
      @facilities = facilities.reject { |x| x.facility_status != 'LICENSED' }
    end
    render template: '/facilities/index'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  # GET /messages
  def index
    @sent_messages = current_user.sent_messages
    @received_messages = current_user.received_messages
  end

  # GET /messages/new
  def new
    @message = Message.new
    @message.sender = current_user
    @message.recipients = []
  end

  # POST /messages
  def create
    message_params = params[:message]
    #{}"message"=>{"recipients"=>"child_1@hanoian.com", "subject"=>"Test subject", "content"=>"Test content"}}
    rcps = message_params[:recipients]
    recipients = User.where('email in (?)', rcps).to_a
    render text: 'No recipients', status: :not_found if recipients.empty?

    message = Message.create(sender: current_user, recipients: recipients, subject: message_params[:subject], content: message_params[:content])  
    @recipient_string =  message.recipients_array.join('<br/>').html_safe
  end

  # GET /messages/:id
  def show
    @disabled = 'disabled'
    @hidden_string = 'hidden=true'
    @message = Message.includes(:sender, :recipients).find(params[:id])
  end

  # GET /messages/:id/edit
  def edit
  end

  # PATCH/PUT /messages/:id
  def update
  end

  # DELETE messages/:id
  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
  end

  def update
    @user = current_user

    user_info = params[:user]

    if (user_info[:password] != user_info[:password_confirmation])
      @status_message = 'Password and Password Confirmation do not match.'
      @bg_class = 'bg-danger'
      render template: 'users/show'
      return
    end

    if (user_info[:password].blank?)
      user_info.reject! { |k, v| k.to_s =~ /^password/ }
    end


    address_info = params[:address]
    if (!valid_address_info?(address_info))
      @status_message = 'Address information is not valid.'
      @bg_class = 'bg-danger'
      render template: 'users/show'
      return
    end

    user_info.each do |k, v|
      @user.send("#{k}=", v)
    end
    @user.save!

    address = @user.addresses.first
    if !address
      address = Address.new
      address.owner = @user
    end
    
    address_info.each do |k, v|
      address.send("#{k}=", v)
    end
    address.save!
    
    @status_message = 'User updated.'
    @bg_class = 'bg-success'
    render template: 'users/show'
  end

  def search
    search_param = params[:q]
    users = User.where("email like '#{search_param.downcase}%' OR first_name like '#{search_param.capitalize}%'").to_a

    results = users.map { |x| {name: x.name, email: x.email } }
    render json: { items: results}
  end

  private
  def valid_address_info?(address_info)
    valid = true
    %w( street city state zip telephone_number).each do |attr|
      valid = false if  address_info[attr.to_sym].blank?
    end
    valid
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/message_helper.rb
module MessageHelper
  LIST_TYPES_MAP = {
    sent_messages: 'to',
    received_messages: 'from'
  }
  # list_type can be :sent_messages or :received_messages 
  def first_column_header(list_type)
    LIST_TYPES_MAP[list_type]
  end

  def msg_to(message)
    result = message.recipients.map(&:name).join(', ')
    string_30(result)
  end

  def msg_from(message)
    result = message.sender.name
    string_30(result)
  end

  def string_30(str)
    (str.size > 30)? str[0..27] + '...' : str
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def input_type(field_name)
    return 'password' if (field_name =~ /^password/ )
    return 'text'
  end
end

app/views/common/_header.erb
<div id="cssmenu">
  <ul>
     <li><a href="/" ><i class="fa fa-fw fa-home"></i> Home</a></li>
     <li><a href="#"><i class="fa fa-fw fa-bars"></i> User Actions</a>
        <ul>
           
           <% if !current_user && controller_name != 'sessions' %>
             <li><a href="/users/sign_in"><i class="fa fa-fw fa-linkedin-square"></i> Login</a></li>
           <% end %>

           <% if current_user %>
             <li><a rel="nofollow" data-method="delete" href="/users/sign_out"><i class="fa fa-fw fa-user-times"></i> Logout</a></li> 
             <li><a href="/users/no_id"><i class="fa fa-fw fa-gear"></i> My Profile</a></li>
           <% end %>  

        </ul>
     </li>

     <% if current_user %>
     <li><a href="#"><i class="fa fa-fw fa-bars"></i> Messages</a>
        <ul>
          <li><a href="/messages/"><i class="fa fa-fw  fa-list-alt"></i> All messages</a></li> 
          <li><a href="/messages/new"><i class="fa fa-fw fa-edit"></i> New message</a></li>
        </ul>
     </li>
     <% end %>

  </ul>
</div>

 

app/views/facilities/_search.erb
 <%= form_for(:facility, as: :facilities, url: '/facilities/search', method: :get) do |f| %>
  <strong>Search by zipcodes:</strong>
  <select class='ui-corner-all col-sm-2', multiple='multiple', id='zipcode_multi_select' name="zipcodes[]"></select>
  
  <button type="submit" id='btn_search' class="btn btn-info btn-sm">
    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    <strong>Search</strong>
  </button>
 <% end %>

app/views/facilities/index.erb
<h3>Facilities</h3>
<br/><br/>
<%= render partial: '/facilities/search' %>
<br/><br/>

<table id="facilities_table" class="table table-bordered display" cellspacing="0">
    <thead>
      <tr class="table success">
        <%  %w( no. facility_type facility_number facility_name licensee administrator 
              regional_office facility_capacity facility_status license_first_date closed_date).each do |attr| %>

            <th><%= attr.humanize %></th>  
        
        <% end %>
        <th>Street</th>
        <th>City</th>
        <th>State</th>
        <th>Zipcode</th>

      </tr>
    </thead>

    <tbody>
      <% @facilities.each_with_index do |facility, idx| %>
        <tr class='tr_clinic_facility' facility_id='<%= facility.id %>' >
          <td><%= idx + 1 %></td>
          <%  %w( facility_type facility_number facility_name licensee administrator_name
              regional_office facility_capacity facility_status licensed_date_string closed_date_string).each do |attr| %>

              <td id='<%= "#{attr}_#{facility.id}" %>' ><%= facility.send(attr) %></td>  
        
          <% end %>
          <td id= ''><%= facility.addresses.first.street  %></td>
          <td id= ''><%= facility.addresses.first.city  %></td>
          <td id= ''><%= facility.addresses.first.state  %></td>
          <td id= ''><%= facility.addresses.first.zip  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FosterCare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>

  <div style="margin-left: 40px; margin-right:40px;" >
    <%= render partial: '/common/header' %>

    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_message_form.erb
<%= form_for(message, as: :messages, url: messages_path, method: :post) do |f| %>
  <br/>
  
  <br/>
  <div class='col-sm-1'><strong>From: </strong></div>
  <div class='col-sm-4'><%= message.sender.name + '  ' %>(<%= message.sender.email %>)</div>
  <br/>
  <br/>

  <div class='col-sm-1'><strong>To: </strong></div>
  <% if @disabled %>
    <div class='col-sm-4'><%= message.recipients_array.join(', ') %></div>
  <% else %>
    <select class='ui-corner-all col-sm-4', multiple='multiple', id='user_multi_select'} name="message[recipients][]"></select>
  <% end %>
  <br/>
  <br/>

  <div class='col-sm-1'><strong>Subject: </strong></div>
  <input <%= @disabled %> class='col-sm-4' type="text" name="message[subject]" id="message_subject" value='<%= message.subject %>' class="text ui-widget-content ui-corner-all" ><br/>
  <br/>
  <div class='col-sm-2'><strong>Content: </strong></div><br/>
  <br/>

  <textarea <%= @disabled %> name="message[content]" id="message_content" class="col-sm-5 ui-corner-all"  rows='10'><%= message.content %></textarea>
  <% 11.times { %> <br/><% } %>

  <div style="float: left;" <%= @hidden_string %> >
    <button type="submit" id='btn_send' class="btn btn-success btn-sm">
      <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
      <strong>Send</strong>
    </button>

    <button type="button" id='btn_cancel' class="btn btn-warning btn-sm" onclick="window.location='/messages'">
      <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
      <strong>Cancel</strong>
    </buton>
  </div>

<% end %>

app/views/messages/_messages_list.erb
<table id="message_list_<%= list_type %>" class="table table-bordered display" cellspacing="0">
  <thead>
    <tr class="table info">
      <th></th>
      <th><%= first_column_header(list_type).humanize %></th>     
      <th>Subject</th>
      <th>Sent Date</th>

    </tr>
  </thead>

  <tbody>
    <% messages.each_with_index do |message, idx| %>
      <tr class='tr_message' message_id='<%= message.id %>' onClick="location.href='/messages/<%= message.id %>'"  style='cursor: pointer;' >
        <td><%= idx + 1 %></td>
        <td><%= self.send("msg_#{first_column_header(list_type)}", message)  %></td>
        <td id= ''><%= message.subject  %></td>
        <td id= ''><%= message.sent_date  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/create.erb
<h3><strong>Message was sent to: </strong></h3><br/>
<%= @recipient_string %>

app/views/messages/index.erb
<h3><strong>Inbox</strong></h3>
<%= render partial: 'messages_list', locals: { messages: @received_messages, list_type: :received_messages} %>

<h3><strong>Sent</strong></h3>
<%= render partial: 'messages_list', locals: { messages: @sent_messages, list_type: :sent_messages} %>

app/views/messages/new.erb
<h3><strong>New Message</strong></h3>
<%= render partial: 'message_form', locals: { message: @message} %>

app/views/messages/show.erb
<h3><strong>Message Content</strong></h3>
<%= render partial: 'message_form', locals: { message: @message} %>

app/views/users/shared/_links.html.erb
<br/>
<br/>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.erb
<h3>My profile</h3>

<% if @status_message %>
  <h3><p class='col-sm-6 text-center <%= @bg_class %>' ><%= @status_message %></p></h3>
  <br/><br/>
<% end %>

<%= form_for(:user, as: :users, url: '/profiles', method: :put) do |f| %>

  <% %w( first_name last_name email password password_confirmation ).each do |attr|  %>
    <div class='col-sm-2'><strong><%= attr.humanize %>: </strong></div>
    <input class='col-sm-4' type="<%= input_type(attr) %>" name="user[<%= attr %>]" id="user_<%= attr %>" value="<%= @user.send(attr) %>" 
      class="text ui-widget-content ui-corner-all" placeholder='Enter new value to change ...'>
    <br/> <br/>
  <% end %>

  <% 
    address_string = 'Address'
    address = @user.addresses.first
    if (!address && @user.facility) 
      address = @user.facility.addresses.first
      address_string += ' (Foster Facility)'
    end
  %>

  <% 2.times { %> <br/> <% } %>

  <h4><%= address_string %></h4>
  <% %w( street city state county_name zip telephone_number ).each do |attr|  %>
    <div class='col-sm-2'><strong><%= attr.humanize %>: </strong></div>

    <input class='col-sm-4' type="text" name="address[<%= attr %>]" id="address_<%= attr %>" value="<%= address&.send(attr)  %>" 
      class="text ui-widget-content ui-corner-all" placeholder='Enter new value to change ...'>

    <br/><br/>
  <% end %>

  <br/><br/>

  <button type="submit" id='btn_send' class="btn btn-success btn-sm">
    <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span>
    <strong>Save</strong>
  </button>

  <button type="button" id='btn_cancel' class="btn btn-warning btn-sm" onclick="window.location='/'" >
    <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
    <strong>Cancel</strong>
  </buton>

<% end %>